services:
  s3-demo-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aws-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - s3-demo-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3-demo-localstack:
    image: localstack/localstack:4.1.0
    environment:
      - SERVICES=s3,dynamodb,sns
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack4/data
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - s3-demo-localstack-data:/tmp/localstack4
      - ./aws-init.sh:/docker-entrypoint-initaws.d/aws-init.sh
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  s3-demo-redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - s3-demo-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  s3-demo-localstack-data:
  s3-demo-postgres-data:
  s3-demo-redis-data: